# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Apigee CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  MAVEN_PROFILE: test
  GIT_BRANCH: main
  AUTHOR_EMAIL: clalevee@gmail.com
  APIGEE_ORG: emea-demo7
  APIGEE_DEPLOYMENT_SUFFIX: ''
  APIGEE_CREDS_USR: ${{ secrets.APIGEE_CREDS_USR }}
  APIGEE_CREDS_PSW: ${{ secrets.APIGEE_CREDS_PSW }}

jobs:
  Apigee-Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Create Dependency Cache 
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` 
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-


    # Install dependency
    - name: Install Dependencies
      run: npm install --silent --no-fund


    - name: apigeelint
      run: ./node_modules/apigeelint/cli.js -s ./apiproxy -f html.js -e PO013 > ./apigeelint-out.html
      

    - name: Archive Apigeeelint results
      uses: actions/upload-artifact@v2
      with:
        name: apigeelint-report
        path: ./apigeelint-out.html
        retention-days: 5


    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2   
    
    - name: mvn-deploy-config
      run:  |
        sed -i "s/target_apigee_env/$MAVEN_PROFILE/g" EdgeConfig/edge.json
        mvn install -P$MAVEN_PROFILE -Dapigee.org=$APIGEE_ORG -Dapigee.username=$APIGEE_CREDS_USR -Dapigee.password=$APIGEE_CREDS_PSW -Dapigee.config.file=./EdgeConfig/edge.json -Dapigee.config.options=update

    - name: mvn-package
      run: mvn process-resources -P$MAVEN_PROFILE -Dcommit=$GIT_COMMIT -Dbranch=$GIT_BRANCH -Dauthor=$AUTHOR_EMAIL -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

    - name: mvn-config
      run: mvn apigee-enterprise:configure -P$MAVEN_PROFILE -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX 
 
    - name: mvn-deploy-proxy
      run: mvn apigee-enterprise:deploy -P$MAVEN_PROFILE -Dapigee.org=$APIGEE_ORG -Dapigee.username=$APIGEE_CREDS_USR -Dapigee.password=$APIGEE_CREDS_PSW -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX
